name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
# Primer paso. toma todo el codigo de mi repositorio para que lo revise
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
# Paso especial, Usando la imagen semantic version, para versionar automaticamente las imagenes                   
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
        id: version


        
# Segundo paso, probar mi autenticación con dockerhub - Creando variable de entorno para usar en otros pasos el versionador
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "Iniciando Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del Login"
        echo "Nueva Version: $NEW_VERSION !!!!!!!!!"
        
# #Tercer paso, construir la imagen
#     - name: Build Docker Image
#       run: |
#          docker build -t focusroot/docker-graphql:0.0.2 .
#          docker build -t focusroot/docker-graphql:latest .
         
# #Cuarto paso, hacer push de la imagen es decir subir la imagen a dockerhub
#     - name: Push Docker Image
#       run: |
#          docker push focusroot/docker-graphql:0.0.2
#          docker push focusroot/docker-graphql:latest



    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
